version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.16.3-browsers

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Install dependencies
          command: npm install
      - save_npm

  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run: npm run build

  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run: npm test -- --no-watch --no-progress

workflows:
  build_and_test:
    jobs:
      - setup
      - build
      - test:
          requires:
            - build
