version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:10.16.3-browsers

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "package-lock.json" }}
  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Install dependencies
          command: npm install
      - save_npm

  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run: npm test -- --no-watch --no-progress

  deploy:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - add_ssh_keys:
          fingerprints:
            - "e1:52:0b:46:0b:75:ce:fc:35:17:5a:80:5a:82:1b:a4"
      - run: git config --global user.name "Circle CI"
      - run: git config --global user.email "<>"
      - run: npm run deploy

workflows:
  build_and_test:
    jobs:
      - setup:
        filters:
          branches:
            ignore: gh-pages
      - test:
          requires:
            - setup
      - deploy:
          requires:
            - setup
          filters:
            branches:
              only:
                - master
